// Package uvm implements the GPU-side UVM remote-access components (plan todo
// 11 of mgpusim-uvm-manager): the GPU-wide AccessCounter and the CPU-remote
// memory endpoint. Both sit behind the UVM access gates and observe remote
// accesses after translation (uvm-manager.md §6.1, §14).
package uvm

// sbin_codex: the UVM coordinator (plan todo 21 of mgpusim-uvm-manager,
// uvm-manager.md §1.2, §10.4, §23.1.1, §26, Scenario F). The coordinator puts
// the timing-neutral UVM handlers behind ONE scheduling + trace authority:
//
//   - both modes (normal and ideal) execute the same functional state machine
//     through the same handlers; only timing differs,
//   - for same-mode scheduling only, every generated root is stamped
//     (kernelLaunchOrdinal, sourceBuildOrdinal, sourceLocalSequence);
//     sourceLocalSequence is a local tie-break and is excluded from
//     cross-mode identity,
//   - cross-mode mandatory program-origin roots use the semantic key
//     (kernelLaunchOrdinal, sourceComponentStableID, originKind, PID, GPU,
//     regionBase, accessKind, programCommandOrdinal); child roots use
//     (parentSemanticKey, edgeLabel, parentLocalOccurrence) so identity
//     follows causality rather than generation time,
//   - child operationOrdinal follows the normative state-machine edges and
//     successors require predecessor completion,
//   - both modes enqueue delivered roots and use one secondary-event
//     serialized drain: normal orders currently-ready work by
//     (actualReadyVTime, sameModeRoot, operationOrdinal) after modeled
//     transport; ideal orders currently-generated work by
//     (currentVTime, sameModeRoot, operationOrdinal) and runs zero-time
//     successors to quiescence,
//   - the coordinator never invents or waits for not-yet-generated roots and
//     never propagates a fake shadow clock through non-UVM execution,
//   - a causal trace DAG (semanticRootKey, operation, predecessorEdges,
//     state/result) is recorded,
//   - mandatory program-origin roots multiset-match and compare by semantic
//     key; reordered independent roots remain unordered,
//   - timing-derived service roots (fault, TBN, Access-Counter, pre-eviction,
//     reactive eviction) may be unmatched across modes only when timing
//     changes whether the service is needed; each unmatched root must carry a
//     valid observed-access/parent provenance, pass the local
//     state-machine/invariant checks, and contribute to the final
//     byte/accounting equations; a duplicate service root for one transition
//     epoch is always failure.
//
// The coordinator exposes no unsupported ordering API: no priorities, no
// global message IDs, and no duplicate state machine.

import (
	"fmt"
	"sort"
	"strings"

	"github.com/sarchlab/akita/v4/mem/vm"
	"github.com/sarchlab/akita/v4/sim"
)

// Mode selects the UVM scheduling mode (uvm-manager.md §1.2).
type Mode int

const (
	// ModeNormal is the modeled-transport UVM mode (-uvm).
	ModeNormal Mode = iota
	// ModeIdeal is the zero-latency UVM mode (-uvm -uvm-ideal): all
	// UVM-specific control-path latency is zeroed while every functional
	// event and counter is preserved.
	ModeIdeal
)

// String returns the mode name.
func (m Mode) String() string {
	if m == ModeIdeal {
		return "ideal"
	}
	return "normal"
}

// OriginKind classifies the origin of a generated root.
type OriginKind int

const (
	// Program-origin kinds: the delivered demands of the program's
	// execution. These roots are mandatory for cross-mode identity: they
	// must multiset-match and compare by semantic key.
	OriginKernelLaunch OriginKind = iota
	OriginFaultRequest
	OriginAccessCounterNotification
	OriginRemoteWrite

	// Timing-derived service kinds: the derived work that services the
	// demands. These roots may be unmatched across modes only when timing
	// changes whether the service is needed; each unmatched root must carry
	// a valid observed-access/parent provenance, pass the local
	// state-machine/invariant checks, and contribute to the final
	// byte/accounting equations. A duplicate service root for one transition
	// epoch is always failure.
	OriginFaultService
	OriginTBNSelection
	OriginAccessCounterMigration
	OriginPreEviction
	OriginReactiveEviction

	// Child-operation kinds: the normative state-machine steps generated by
	// a service (replay, DMA, TLB invalidation, cache flush). They follow
	// their parent's causality and are compared as part of the matched
	// root DAGs.
	OriginReplay
	OriginDMA
	OriginTLBInvalidate
	OriginCacheFlush
)

// String returns the origin kind name.
func (k OriginKind) String() string {
	switch k {
	case OriginKernelLaunch:
		return "kernel-launch"
	case OriginFaultRequest:
		return "fault-request"
	case OriginAccessCounterNotification:
		return "access-counter-notification"
	case OriginRemoteWrite:
		return "remote-write"
	case OriginFaultService:
		return "fault-service"
	case OriginTBNSelection:
		return "tbn-selection"
	case OriginAccessCounterMigration:
		return "access-counter-migration"
	case OriginPreEviction:
		return "pre-eviction"
	case OriginReactiveEviction:
		return "reactive-eviction"
	case OriginReplay:
		return "replay"
	case OriginDMA:
		return "dma"
	case OriginTLBInvalidate:
		return "tlb-invalidate"
	case OriginCacheFlush:
		return "cache-flush"
	}
	return fmt.Sprintf("origin(%d)", int(k))
}

// ProgramOrigin reports whether the kind is a mandatory program-origin root.
func (k OriginKind) ProgramOrigin() bool {
	switch k {
	case OriginKernelLaunch, OriginFaultRequest,
		OriginAccessCounterNotification, OriginRemoteWrite:
		return true
	}
	return false
}

// ServiceRoot reports whether the kind is a timing-derived service root
// subject to the duplicate-transition-epoch rule (uvm-manager.md §1.2).
func (k OriginKind) ServiceRoot() bool {
	switch k {
	case OriginFaultService, OriginTBNSelection,
		OriginAccessCounterMigration, OriginPreEviction,
		OriginReactiveEviction:
		return true
	}
	return false
}

// SemanticRootKey is the cross-mode identity of a mandatory program-origin
// root: (kernelLaunchOrdinal, sourceComponentStableID, originKind, PID, GPU,
// regionBase, accessKind, programCommandOrdinal). The same-mode stamp's
// sourceLocalSequence is deliberately absent: it is a local tie-break,
// excluded from cross-mode identity.
type SemanticRootKey struct {
	KernelLaunchOrdinal     uint64
	SourceComponentStableID string
	OriginKind              OriginKind
	PID                     vm.PID
	GPU                     int
	RegionBase              uint64
	AccessKind              vm.AccessKind
	ProgramCommandOrdinal   uint64
}

// String returns the canonical key string.
func (k SemanticRootKey) String() string {
	return fmt.Sprintf("root{%d|%s|%s|%d|%d|%#x|%d|%d}",
		k.KernelLaunchOrdinal, k.SourceComponentStableID, k.OriginKind,
		k.PID, k.GPU, k.RegionBase, k.AccessKind, k.ProgramCommandOrdinal)
}

// Equal reports whether two semantic keys are identical.
func (k SemanticRootKey) Equal(o SemanticRootKey) bool {
	return k == o
}

// ChildSemanticKey is the identity of a generated child root: identity
// follows causality (parentKey, edgeLabel, parentLocalOccurrence) rather
// than generation time. parentKey is the parent's canonical key (the
// semantic key for the first generation, a child key for deeper
// generations).
type ChildSemanticKey struct {
	ParentKey             string
	EdgeLabel             string
	ParentLocalOccurrence uint64
}

// String returns the canonical key string.
func (k ChildSemanticKey) String() string {
	return fmt.Sprintf("child{%s|%s|%d}",
		k.ParentKey, k.EdgeLabel, k.ParentLocalOccurrence)
}

// SameModeStamp is the local scheduling stamp of a generated root: the
// kernel-launch ordinal, the source build ordinal, and the source-local
// sequence. The sequence is a local tie-break: it is excluded from
// cross-mode identity. Children inherit the parent's stamp (they belong to
// the same episode).
type SameModeStamp struct {
	KernelLaunchOrdinal uint64
	SourceBuildOrdinal  uint64
	SourceLocalSequence uint64
}

// less orders stamps for the same-mode scheduling key.
func (s SameModeStamp) less(o SameModeStamp) bool {
	if s.KernelLaunchOrdinal != o.KernelLaunchOrdinal {
		return s.KernelLaunchOrdinal < o.KernelLaunchOrdinal
	}
	if s.SourceBuildOrdinal != o.SourceBuildOrdinal {
		return s.SourceBuildOrdinal < o.SourceBuildOrdinal
	}
	return s.SourceLocalSequence < o.SourceLocalSequence
}

// Edge is one predecessor edge of a trace node.
type Edge struct {
	From  string
	Label string
}

// Root is one generated UVM root: a delivered program-origin root (semantic
// key identity) or a generated child root (child key identity).
type Root struct {
	// Identity: a program-origin root carries SemanticKey; a generated
	// child root carries ChildKey (set by the coordinator's adoption).
	SemanticKey SemanticRootKey
	ChildKey    *ChildSemanticKey

	// Stamp is the same-mode scheduling stamp (children inherit the
	// parent's stamp).
	Stamp SameModeStamp

	// EdgeLabel is the edge from the parent (empty for delivered roots).
	EdgeLabel string

	// Operation is the timing-neutral operation that services this root.
	Operation string

	// CurrentVTime is the generation time of the root.
	CurrentVTime sim.VTimeInSec
	// ActualReadyVTime is the time the root becomes ready: after the
	// modeled transport in normal mode, at the generation time in ideal
	// mode.
	ActualReadyVTime sim.VTimeInSec
	// OperationOrdinal follows the normative state-machine edges: a child
	// of operation ordinal n has ordinal n+1 (n+1+i for the i-th child in
	// normative order).
	OperationOrdinal uint64

	// Predecessors are the causal predecessor edges; successors require
	// predecessor completion.
	Predecessors []Edge

	// Provenance is the observed-access/parent provenance of a
	// timing-derived service root.
	Provenance string

	// TimingDerived marks a root whose existence depends on timing (e.g. a
	// refault caused by a timing-derived eviction). Only such roots may be
	// unmatched across modes.
	TimingDerived bool

	// Execution record.
	State  string
	Result string
	Bytes  uint64
	Done   bool

	// completed is set by Complete (the asynchronous driver path).
	completed bool
	// handlerCalled marks a root whose handler ran but the operation
	// completes asynchronously (it waits for the completion report).
	handlerCalled bool
	// completionTime is the reported completion time.
	completionTime sim.VTimeInSec
}

// Key returns the canonical identity of the root.
func (r *Root) Key() string {
	if r.ChildKey != nil {
		return r.ChildKey.String()
	}
	return r.SemanticKey.String()
}

// regionKey returns the (PID, GPU, regionBase) of the root.
func (r *Root) regionKey() regionKey {
	return regionKey{
		pid:        r.SemanticKey.PID,
		gpu:        r.SemanticKey.GPU,
		regionBase: r.SemanticKey.RegionBase,
	}
}

// Handler is one timing-neutral UVM operation behind the coordinator. The
// handler executes the operation for a root and returns the generated child
// roots (zero-time successors in ideal mode; each child carries its own
// modeled transport in normal mode), the resulting region state, the
// operation result, and whether the operation completed synchronously. A
// handler that completes asynchronously (the driver middlewares) returns
// done=false; the coordinator records the completion when it is reported.
type Handler interface {
	Handle(root *Root) (children []*Root, state, result string, done bool)
}

// HandlerFunc adapts a function to the Handler interface.
type HandlerFunc func(root *Root) (children []*Root, state, result string, done bool)

// Handle implements Handler.
func (f HandlerFunc) Handle(root *Root) ([]*Root, string, string, bool) {
	return f(root)
}

// TraceNode is one node of the causal trace DAG:
// (semanticRootKey, operation, predecessorEdges, state/result).
type TraceNode struct {
	Key              string
	Operation        string
	PredecessorEdges []Edge
	State            string
	Result           string
	Bytes            uint64
}

// TraceDAG records the causal trace of the executed roots.
type TraceDAG struct {
	nodes []*TraceNode
	byKey map[string]*TraceNode
}

// Nodes returns the recorded trace nodes in execution order.
func (d *TraceDAG) Nodes() []*TraceNode {
	return d.nodes
}

// Node returns the trace node of a key, or nil.
func (d *TraceDAG) Node(key string) *TraceNode {
	return d.byKey[key]
}

// Len returns the number of recorded nodes.
func (d *TraceDAG) Len() int {
	return len(d.nodes)
}

// Equal reports whether the other DAG records exactly the same nodes: the
// same key set with equal (operation, predecessorEdges, state, result,
// bytes) per node. Execution order is not compared: reordered independent
// roots remain unordered.
func (d *TraceDAG) Equal(o *TraceDAG) bool {
	if len(d.nodes) != len(o.nodes) {
		return false
	}
	for _, n := range d.nodes {
		on := o.byKey[n.Key]
		if on == nil {
			return false
		}
		if n.Operation != on.Operation || n.State != on.State ||
			n.Result != on.Result || n.Bytes != on.Bytes {
			return false
		}
		if !edgeSetEqual(n.PredecessorEdges, on.PredecessorEdges) {
			return false
		}
	}
	return true
}

// edgeSetEqual compares two predecessor edge sets ignoring order.
func edgeSetEqual(a, b []Edge) bool {
	if len(a) != len(b) {
		return false
	}
	as := make([]string, len(a))
	bs := make([]string, len(b))
	for i, e := range a {
		as[i] = e.From + "|" + e.Label
	}
	for i, e := range b {
		bs[i] = e.From + "|" + e.Label
	}
	sort.Strings(as)
	sort.Strings(bs)
	for i := range as {
		if as[i] != bs[i] {
			return false
		}
	}
	return true
}

// epochServiceKey identifies one serviced transition epoch of one region for
// one service kind.
type epochServiceKey struct {
	region regionKey
	epoch  uint64
	kind   OriginKind
}

// Coordinator is the one scheduling + trace authority behind the
// timing-neutral UVM handlers.
type Coordinator struct {
	mode Mode

	// transport is the modeled transport of an operation in normal mode
	// (ideal mode ignores it: every control latency is zero).
	transport func(root *Root) sim.VTimeInSec

	handlers map[string]Handler

	// pending is the enqueued-but-not-executed roots in enqueue order
	// (the stable tie-break for equal ordering keys).
	pending []*Root
	// byKey maps every executed root's canonical key to the root.
	byKey map[string]*Root

	// childCounts counts the generated children per (parentKey, edgeLabel)
	// for the parentLocalOccurrence.
	childCounts map[string]map[string]uint64

	// trace is the causal trace DAG.
	trace *TraceDAG

	// epochs tracks the per-region transition epochs.
	epochs map[regionKey]uint64
	// states tracks the per-region residency state.
	states map[regionKey]string
	// serviced records the service roots per (region, epoch, kind).
	serviced map[epochServiceKey]bool

	// provenances is the registry of valid observed-access/parent
	// provenance strings.
	provenances map[string]bool

	// bytes is the total logical bytes of the executed roots.
	bytes uint64
	// latency is the total UVM control latency of the executed roots
	// (zero in ideal mode).
	latency sim.VTimeInSec

	// failures collects every invariant failure.
	failures []string
	// failed maps a root key to its execution failure reason.
	failed map[string]string
}

// NewCoordinator constructs a coordinator for the mode.
func NewCoordinator(mode Mode) *Coordinator {
	return &Coordinator{
		mode:        mode,
		handlers:    make(map[string]Handler),
		byKey:       make(map[string]*Root),
		childCounts: make(map[string]map[string]uint64),
		trace:       &TraceDAG{byKey: make(map[string]*TraceNode)},
		epochs:      make(map[regionKey]uint64),
		states:      make(map[regionKey]string),
		serviced:    make(map[epochServiceKey]bool),
		provenances: make(map[string]bool),
		failed:      make(map[string]string),
	}
}

// Mode returns the scheduling mode.
func (c *Coordinator) Mode() Mode {
	return c.mode
}

// SetTransport sets the modeled transport of an operation in normal mode.
// The transport function receives the root so the model can be per-region or
// per-operation. Ideal mode ignores the transport (zero latency).
func (c *Coordinator) SetTransport(fn func(root *Root) sim.VTimeInSec) {
	c.transport = fn
}

// RegisterHandler registers the timing-neutral handler of an operation.
func (c *Coordinator) RegisterHandler(op string, h Handler) {
	c.handlers[op] = h
}

// RegisterProvenance registers a valid observed-access/parent provenance
// string. An unmatched timing-derived service root is accepted only when its
// provenance is registered (or it has a parent).
func (c *Coordinator) RegisterProvenance(p string) {
	c.provenances[p] = true
}

// Enqueue delivers a generated root to the coordinator. Both modes enqueue
// delivered roots; the coordinator applies the modeled transport in normal
// mode and zero latency in ideal mode. The coordinator never invents or
// waits for not-yet-generated roots.
func (c *Coordinator) Enqueue(root *Root) {
	if root.ChildKey == nil && root.SemanticKey == (SemanticRootKey{}) {
		c.fail("enqueued root without identity")
		return
	}
	if c.mode == ModeIdeal {
		root.ActualReadyVTime = root.CurrentVTime
	} else if root.ActualReadyVTime == 0 && c.transport != nil {
		root.ActualReadyVTime = root.CurrentVTime + c.transport(root)
	}
	c.pending = append(c.pending, root)
}

// Complete reports the asynchronous completion of a root (the driver path:
// the middleware completes the operation and reports the resulting state,
// result, logical bytes, and the completion time). The coordinator records
// the trace node at the next drain.
func (c *Coordinator) Complete(
	root *Root,
	state, result string,
	bytes uint64,
	now sim.VTimeInSec,
) {
	root.State = state
	root.Result = result
	root.Bytes = bytes
	root.completed = true
	root.completionTime = now
	c.applyStateChange(root, state)
}

// Drain is the one secondary-event serialized drain: it executes the
// currently-ready roots one at a time in the mode's total order and returns
// the number of roots executed. Normal mode orders currently-ready work by
// (actualReadyVTime, sameModeRoot, operationOrdinal) after modeled
// transport; ideal mode orders currently-generated work by
// (currentVTime, sameModeRoot, operationOrdinal) and runs zero-time
// successors to quiescence. The drain stops when no enqueued root is
// currently ready: it never waits for or invents not-yet-generated roots.
func (c *Coordinator) Drain(now sim.VTimeInSec) int {
	executed := 0
	for {
		root := c.pickReady(now)
		if root == nil {
			break
		}
		c.execute(root)
		executed++
	}
	return executed
}

// NextReadyTime returns the earliest ready time of the pending roots and
// whether any pending root exists. The caller schedules the next drain at
// that time (normal mode).
func (c *Coordinator) NextReadyTime() (sim.VTimeInSec, bool) {
	best := sim.VTimeInSec(0)
	found := false
	for _, r := range c.pending {
		if r.Done {
			continue
		}
		if !found || r.ActualReadyVTime < best {
			best = r.ActualReadyVTime
			found = true
		}
	}
	return best, found
}

// Trace returns the causal trace DAG.
func (c *Coordinator) Trace() *TraceDAG {
	return c.trace
}

// TotalBytes returns the total logical bytes of the executed roots.
func (c *Coordinator) TotalBytes() uint64 {
	return c.bytes
}

// TotalLatency returns the total UVM control latency of the executed roots
// (zero in ideal mode).
func (c *Coordinator) TotalLatency() sim.VTimeInSec {
	return c.latency
}

// Failures returns every invariant failure recorded by the coordinator.
func (c *Coordinator) Failures() []string {
	return append([]string(nil), c.failures...)
}

// pickReady selects the currently-ready root with the minimal
// (readyTime, sameModeRoot, operationOrdinal) key whose predecessors are
// complete. Ties are broken by the enqueue order (stable).
func (c *Coordinator) pickReady(now sim.VTimeInSec) *Root {
	var best *Root
	for _, r := range c.pending {
		if r.Done || (r.handlerCalled && !r.completed) {
			continue
		}
		if r.ActualReadyVTime > now {
			continue
		}
		if !c.predecessorsDone(r) {
			continue
		}
		if best == nil || c.less(r, best) {
			best = r
		}
	}
	return best
}

// predecessorsDone reports whether every predecessor of the root has
// completed.
func (c *Coordinator) predecessorsDone(r *Root) bool {
	for _, e := range r.Predecessors {
		p := c.byKey[e.From]
		if p == nil || !p.Done {
			return false
		}
	}
	return true
}

// less orders two roots by (readyTime, sameModeRoot, operationOrdinal).
func (c *Coordinator) less(a, b *Root) bool {
	if a.ActualReadyVTime != b.ActualReadyVTime {
		return a.ActualReadyVTime < b.ActualReadyVTime
	}
	if !a.Stamp.less(b.Stamp) && !b.Stamp.less(a.Stamp) {
		if a.OperationOrdinal != b.OperationOrdinal {
			return a.OperationOrdinal < b.OperationOrdinal
		}
		// Stable tie-break: the enqueue order (the pending slice is kept
		// in enqueue order).
		return false
	}
	return a.Stamp.less(b.Stamp)
}

// execute runs one ready root: an asynchronously completed root is recorded
// directly; otherwise the duplicate-transition-epoch and provenance checks
// for service roots run, the registered handler executes (or the root stays
// pending for its asynchronous completion), the trace is recorded, and the
// generated children are adopted.
func (c *Coordinator) execute(root *Root) {
	if root.completed {
		c.removePending(root)
		c.record(root)
		root.Done = true
		return
	}

	if root.SemanticKey.OriginKind.ServiceRoot() {
		key := epochServiceKey{
			region: root.regionKey(),
			epoch:  c.epochs[root.regionKey()],
			kind:   root.SemanticKey.OriginKind,
		}
		if c.serviced[key] {
			c.failRoot(root, fmt.Sprintf(
				"duplicate service root for one transition epoch: %s",
				root.Key()))
			return
		}
		c.serviced[key] = true
		if root.Provenance == "" {
			c.failRoot(root, fmt.Sprintf(
				"service root without provenance: %s", root.Key()))
			return
		}
	}

	handler, ok := c.handlers[root.Operation]
	if !ok {
		c.failRoot(root, fmt.Sprintf(
			"no handler for operation %q (%s)", root.Operation, root.Key()))
		return
	}
	children, state, result, done := handler.Handle(root)
	root.State = state
	root.Result = result
	if done {
		root.Done = true
		c.removePending(root)
		c.record(root)
		c.applyStateChange(root, state)
		for i, child := range children {
			c.adoptChild(root, child, i)
			c.Enqueue(child)
		}
		return
	}
	root.handlerCalled = true
}

// failRoot records an execution failure for a root and records its trace
// node with the failure result.
func (c *Coordinator) failRoot(root *Root, reason string) {
	c.fail(reason)
	c.failed[root.Key()] = reason
	root.State = "FAILED"
	root.Result = reason
	root.Done = true
	c.record(root)
}

// fail records a coordinator-level failure.
func (c *Coordinator) fail(reason string) {
	c.failures = append(c.failures, reason)
}

// removePending removes a root from the pending set.
func (c *Coordinator) removePending(root *Root) {
	for i, r := range c.pending {
		if r == root {
			c.pending = append(c.pending[:i], c.pending[i+1:]...)
			return
		}
	}
}

// record records the root's trace node.
func (c *Coordinator) record(root *Root) {
	node := &TraceNode{
		Key:              root.Key(),
		Operation:        root.Operation,
		PredecessorEdges: append([]Edge(nil), root.Predecessors...),
		State:            root.State,
		Result:           root.Result,
		Bytes:            root.Bytes,
	}
	c.trace.nodes = append(c.trace.nodes, node)
	c.trace.byKey[root.Key()] = node
	c.byKey[root.Key()] = root
	c.bytes += root.Bytes
	if root.completed {
		c.latency += root.completionTime - root.CurrentVTime
	} else {
		c.latency += root.ActualReadyVTime - root.CurrentVTime
	}
}

// applyStateChange advances the region's transition epoch when the reported
// state differs from the tracked state. The first report of a region
// establishes the baseline (no transition).
func (c *Coordinator) applyStateChange(root *Root, state string) {
	key := root.regionKey()
	if state == "" {
		return
	}
	if c.states[key] == "" {
		c.states[key] = state
		return
	}
	if c.states[key] != state {
		c.epochs[key]++
		c.states[key] = state
	}
}

// adoptChild adopts a generated child root: it inherits the parent's
// same-mode stamp, follows the normative state-machine edges (operation
// ordinal = parent + 1 + i), receives its child semantic key
// (parentKey, edgeLabel, parentLocalOccurrence), inherits the parent's
// region identity with its own operation kind, and carries the
// mode-appropriate timing.
func (c *Coordinator) adoptChild(parent, child *Root, idx int) {
	child.Stamp = parent.Stamp
	child.OperationOrdinal = parent.OperationOrdinal + 1 + uint64(idx)
	if child.SemanticKey == (SemanticRootKey{}) {
		child.SemanticKey = parent.SemanticKey
		child.SemanticKey.OriginKind = kindForOperation(child.Operation)
	}
	occurrence := c.childCounts[parent.Key()][child.EdgeLabel]
	if c.childCounts[parent.Key()] == nil {
		c.childCounts[parent.Key()] = make(map[string]uint64)
	}
	c.childCounts[parent.Key()][child.EdgeLabel] = occurrence + 1
	child.ChildKey = &ChildSemanticKey{
		ParentKey:             parent.Key(),
		EdgeLabel:             child.EdgeLabel,
		ParentLocalOccurrence: occurrence,
	}
	child.Predecessors = append(child.Predecessors, Edge{
		From:  parent.Key(),
		Label: child.EdgeLabel,
	})
	if child.Provenance == "" {
		child.Provenance = parent.Key()
	}
	child.CurrentVTime = parent.ActualReadyVTime
	if c.mode == ModeIdeal {
		child.ActualReadyVTime = child.CurrentVTime
	} else if c.transport != nil {
		child.ActualReadyVTime = child.CurrentVTime + c.transport(child)
	}
}

// kindForOperation maps a timing-neutral operation to its origin kind.
func kindForOperation(op string) OriginKind {
	switch op {
	case "fault-service":
		return OriginFaultService
	case "tbn-selection":
		return OriginTBNSelection
	case "access-counter-migration":
		return OriginAccessCounterMigration
	case "pre-eviction":
		return OriginPreEviction
	case "reactive-eviction":
		return OriginReactiveEviction
	case "replay":
		return OriginReplay
	case "dma-h2d", "dma-d2h":
		return OriginDMA
	case "tlb-invalidate":
		return OriginTLBInvalidate
	case "cache-flush":
		return OriginCacheFlush
	}
	return OriginFaultService
}

// executedRoots returns the executed roots sorted by canonical key.
func (c *Coordinator) executedRoots() []*Root {
	roots := make([]*Root, 0, len(c.byKey))
	for _, r := range c.byKey {
		roots = append(roots, r)
	}
	sort.Slice(roots, func(i, j int) bool {
		return roots[i].Key() < roots[j].Key()
	})
	return roots
}

// ExecutedRoots returns the executed roots (test/control accessor).
func (c *Coordinator) ExecutedRoots() []*Root {
	return c.executedRoots()
}

// RootPair is one cross-mode matched root pair.
type RootPair struct {
	A *Root
	B *Root
}

// UnmatchedRoot is one locally justified unmatched root of one mode.
type UnmatchedRoot struct {
	Mode Mode
	Root *Root
}

// MatchResult is the outcome of a cross-mode comparison.
type MatchResult struct {
	// Pairs lists the multiset-matched roots (by canonical key).
	Pairs []RootPair
	// Unmatched lists each mode's unmatched roots.
	Unmatched []UnmatchedRoot
	// Failures lists every cross-mode validation failure.
	Failures []string
}

// Match compares this coordinator's executed trace with the other mode's.
// Mandatory program-origin roots must multiset-match and compare by semantic
// key; reordered independent roots remain unordered. Timing-derived service
// roots may be unmatched only when timing changes whether the service is
// needed: each unmatched root must carry a valid observed-access/parent
// provenance, pass the local state-machine/invariant checks (no duplicate
// transition epoch), and contribute to the final byte/accounting equations.
func (c *Coordinator) Match(other *Coordinator) *MatchResult {
	result := &MatchResult{}
	a := c.executedRoots()
	b := other.executedRoots()

	// Multiset-match by canonical key.
	usedB := make(map[*Root]bool)
	for _, ra := range a {
		var partner *Root
		for _, rb := range b {
			if usedB[rb] || rb.Key() != ra.Key() {
				continue
			}
			partner = rb
			break
		}
		if partner == nil {
			c.validateUnmatched(ModeNormal, ra, c)
			result.Unmatched = append(result.Unmatched,
				UnmatchedRoot{Mode: ModeNormal, Root: ra})
			continue
		}
		usedB[partner] = true
		result.Pairs = append(result.Pairs, RootPair{A: ra, B: partner})
		if !c.sameNode(ra, partner) {
			result.Failures = append(result.Failures, fmt.Sprintf(
				"matched roots differ: %s (%s/%s/%s/%d vs %s/%s/%s/%d)",
				ra.Key(), ra.Operation, ra.State, ra.Result, ra.Bytes,
				partner.Operation, partner.State, partner.Result,
				partner.Bytes))
		}
	}
	for _, rb := range b {
		if usedB[rb] {
			continue
		}
		other.validateUnmatched(ModeIdeal, rb, other)
		result.Unmatched = append(result.Unmatched,
			UnmatchedRoot{Mode: ModeIdeal, Root: rb})
	}

	// The matched roots' trace nodes (operation, state, result, bytes,
	// predecessor edges) were compared above; unmatched roots are compared
	// only by their local justification, never by their total order
	// (reordered independent roots remain unordered).

	// The execution failures of both modes are always failures.
	result.Failures = append(result.Failures, c.failures...)
	result.Failures = append(result.Failures, other.failures...)

	return result
}

// sameNode compares the trace node of two matched roots.
func (c *Coordinator) sameNode(a, b *Root) bool {
	return a.Operation == b.Operation && a.State == b.State &&
		a.Result == b.Result && a.Bytes == b.Bytes &&
		edgeSetEqual(a.Predecessors, b.Predecessors)
}

// validateUnmatched validates one unmatched root: a mandatory program-origin
// root that is not timing-derived is always a failure; a timing-derived or
// service root is accepted only with a valid observed-access/parent
// provenance, local legality (no duplicate transition epoch), and an
// accounting contribution (its bytes are reported for the final
// byte/accounting equations).
func (c *Coordinator) validateUnmatched(mode Mode, root *Root, owner *Coordinator) {
	if reason, failed := owner.failed[root.Key()]; failed {
		c.failures = append(c.failures, fmt.Sprintf(
			"unmatched root failed locally: %s (%s)", root.Key(), reason))
		return
	}
	if root.SemanticKey.OriginKind.ProgramOrigin() && !root.TimingDerived {
		c.failures = append(c.failures, fmt.Sprintf(
			"unmatched mandatory program-origin root: %s", root.Key()))
		return
	}
	if !owner.validProvenance(root) {
		c.failures = append(c.failures, fmt.Sprintf(
			"unmatched root without valid provenance: %s", root.Key()))
	}
}

// validProvenance reports whether the root carries a valid
// observed-access/parent provenance.
func (c *Coordinator) validProvenance(root *Root) bool {
	if root.Provenance == "" {
		return false
	}
	if c.provenances[root.Provenance] {
		return true
	}
	for _, e := range root.Predecessors {
		if e.From == root.Provenance {
			return true
		}
	}
	return false
}

// provenanceOf builds the canonical observed-access provenance string of a
// root's region (used by the driver wiring and the fixtures).
func provenanceOf(pid vm.PID, gpu int, regionBase uint64, kind vm.AccessKind) string {
	return fmt.Sprintf("observed-access:pid=%d,gpu=%d,region=%#x,kind=%d",
		pid, gpu, regionBase, kind)
}

// parseProvenanceRegion extracts the region base of an observed-access
// provenance string ("" when the string is not an observed-access
// provenance).
func parseProvenanceRegion(p string) string {
	const prefix = "observed-access:region="
	i := strings.Index(p, prefix)
	if i < 0 {
		return ""
	}
	rest := p[i+len(prefix):]
	j := strings.Index(rest, ",")
	if j < 0 {
		return rest
	}
	return rest[:j]
}