#!/bin/bash
# sbin_gmmu_omo: refresh the compiled binaries inside the copied sample tree.
# Requires 2_copy_benchmarks.sh to have run first.

# benchmarks=(
#     'altis_cfd'
#     'atax'
#     'babelstream'
#     'bfs'
#     'bicg'
#     'cache_latency'
#     'fastwalshtransform'
#     'fft'
#     'fir'
#     'floydwarshall'
#     'kmeans'
#     'matrixtranspose'
#     'nbody'
#     'npb_ep'
#     'parboil_cutcp'
#     'parboil_sgemm'
#     'polybench_2dconv'
#     'polybench_3dconv'
#     'polybench_3mm'
#     'polybench_correlation'
#     'polybench_fdtd2d'
#     'polybench_gemm'
#     'polybench_jacobi2d'
#     'polybench_mvt'
#     'polybench_syr2k'
#     'relu'
#     'rodinia_backprop'
#     'rodinia_gaussian'
#     'rodinia_hotspot'
#     'rodinia_hotspot3d'
#     'rodinia_lavamd'
#     'rodinia_lud'
#     'rodinia_pathfinder'
#     'rodinia_srad'
#     'spmv'
#     'stencil2d'
#     'tango_blackscholes'
#     'vectoradd'
#     'polybench_doitgen'
#     'polybench_gemver'
#     'polybench_gesummv'
#     'polybench_jacobi1d'
#     'polybench_lu'
#     'pannotia_color'
#     'pannotia_mis'
#     'pannotia_sssp'
#     'gups'
#     'reduction'
#     'graphbig_betweennesscentr'
#     'graphbig_bfs'
#     'graphbig_connectedcomp'
#     'graphbig_degreecentr'
#     'graphbig_gc'
#     'graphbig_kcore'
#     'graphbig_sssp'
#     'graphbig_trianglecount'
# )

# sbin_claude: integrated benchmark set, kept in sync with
# 1_compile_benchmarks.py and 3_gen_runners.py.
benchmarks=(
    'altis_cfd'
    'atax'
    'babelstream'
    'bfs'
    'bicg'
    'cache_latency'
    'fastwalshtransform'
    'fft'
    'fir'
    'floydwarshall'
    'graphbig_betweennesscentr'
    'graphbig_bfs'
    'graphbig_connectedcomp'
    'graphbig_degreecentr'
    'graphbig_gc'
    'graphbig_kcore'
    'graphbig_sssp'
    'graphbig_trianglecount'
    'gups'
    'kmeans'
    'matrixmultiplication'
    'matrixtranspose'
    'nbody'
    'npb_ep'
    'nw'
    'pagerank'
    'pannotia_color'
    'pannotia_mis'
    'pannotia_sssp'
    'parboil_cutcp'
    'parboil_sgemm'
    'polybench_2dconv'
    'polybench_3dconv'
    'polybench_3mm'
    'polybench_correlation'
    'polybench_doitgen'
    'polybench_fdtd2d'
    'polybench_gemm'
    'polybench_gemver'
    'polybench_gesummv'
    'polybench_jacobi1d'
    'polybench_jacobi2d'
    'polybench_lu'
    'polybench_mvt'
    'polybench_syr2k'
    'reduction'
    'relu'
    'rodinia_backprop'
    'rodinia_gaussian'
    'rodinia_hotspot'
    'rodinia_hotspot3d'
    'rodinia_lavamd'
    'rodinia_lud'
    'rodinia_pathfinder'
    'rodinia_srad'
    'simpleconvolution'
    'spmv'
    'stencil2d'
    'tango_blackscholes'
    'vectoradd'
)

for benchmark in ${benchmarks[@]};
do
    echo $benchmark
    cp ../mgpusim/amd/samples/${benchmark}/${benchmark} benchmarks/samples/${benchmark}/.
done
